### ISSUE TITLE
readme 头图挂了

### ISSUE THREAD

**Issue by vanishcode** [raptazure/daily-tarot#1]
话说，宁也是塔罗师？

![IMG_0999](https://user-images.githubusercontent.com/20496444/83256128-72459680-a1e4-11ea-9d48-9b9bb60f517e.JPG)

**Comment by raptazure** [comment]
哇花影好评！我用的是棱镜～
头图的话，现在是需要梯子（因为当时直接用 github 托管的图片，前一段时间不知咋的 `raw.githubusercontent.com` 好像被墙了），等着我传到别的图床上hh

**Comment by vanishcode** [comment]
XD 挂了梯子能看了

**Comment by joyous-coder** [comment]
每天搬砖前卜上一卦 😄
